### ISSUE TITLE
update korm version

### ISSUE THREAD

**Issue by kamalshkeir** [kokizzu/gorm-vs-korm#1]
Hello bro, nice repos
korm GetRowS and GetRowM should be faster using latest version v1.4.1 (without cache).
Are you aiming to add results with korm cache enabled also ?, because korm cache can stay enabled, and whenever you create, update, delete or drop the cache is automatically freed, you can also empty the cache manually using korm.FlushCache() if it is causing problem for some queries

**Comment by kokizzu** [comment]
ok trying

**Comment by kokizzu** [comment]
the cache won't work for me, because it has unlimited memory, if my database greater than the RAM it would OOM

**Comment by kokizzu** [comment]
updated

**Comment by kamalshkeir** [comment]
Thank you, great work, and yeah i didn't worry a lot about the memory consumption because the cron running every korm.FlushCacheEvery 10 min by default to Flush the cache, and also because the cache is cleaned every create update delete and drop, so do you have any idea how can i limit the cache to not exceed the RAM ?

also i see the updated benchmarks, not on the favor of korm :) ,  but i expected , cache is adding a little bit of stuff to everything and also my recent support of concat and len for all dialects seamlessly in where will also decrease performance of GetRowS and M , all to support this kind of query https://github.com/kamalshkeir/korm#example-concat-and-len-from-korm_testgo :/
